version: "3.9"
services:
  api:
    build: ./apps/api
    environment:
      - DATABASE_URL=sqlite:///./dev.db
      - CORS_ORIGINS=http://127.0.0.1:3000,http://localhost:3000
    ports: ["8000:8000"]

  web:
    build: ./apps/web
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
    ports: ["3000:3000"]
    depends_on: [api]